### ISSUE TITLE
Integrate tmux / vim

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [kaihowl/dotfiles#115]
I want to seamlessly switch between windows in vim and panes without switching / rethinking.

**Comment by kaihowl** [comment]
https://github.com/christoomey/vim-tmux-navigator

This might require using new keybindings instead of the existing ones.

**Comment by kaihowl** [comment]
The default key bindings conflict with fzf's maps to navigate up/down. Trying to set alternative key maps involves either using the metakey or involves using multi-modifier mappings that I had trouble getting to work in vim.

With an alacritty adaptation for the for sending the correct keystrokes on pressing the meta key it seems to be working.
