### ISSUE TITLE
When quickfix window is the only open window, still allow to start :Make

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [kaihowl/dotfiles#117]
Currently, you can the error "cannot close last window"

**Comment by kaihowl** [comment]
Checking upstream: https://github.com/tpope/vim-dispatch/issues/323

We could try finding a way to remap `cclose` to a user-defined function with a check on `getwininfo()` to identify that the last window open is a quickfix window and then map `cclose` to nop.

Alternatively, we additionally open NerdTree with `:e .`. This might be an odd behavior, though. It matches my usual, manual work-around, though.

**Comment by kaihowl** [comment]
Better work around: Use `:bp` to go to the previous buffer. This might be a more consistent approach as I tend to close the previous buffer by using `<ctrl-w>o`.

**Comment by kaihowl** [comment]
First fix upstream. Reported further problems on the upstream ticket. Locally, I see an issue with this autocommand group interfering (unexpectedly so).

https://github.com/kaihowl/dotfiles/blob/6926039f9c866bc95722e53480b5a44949732c76/nvim/config--nvim--init.vim.symlink#L377-L381

This should probably be nuked. I don't use the ability to call `grep` directly. Let alone the ability to have `lgrep` populate the location list. Therefore, let's remove this and call `copen` directly. This forgoes the ability to have the quickfix only open when there is a match at all. I like this explicitness of an empty, open window, though.

**Comment by kaihowl** [comment]
With `911b94995243719fd2dc8743ce8a5b239b8adfbc`, I can no longer reproduce the issue.
