### ISSUE TITLE
ctrl-c for docker-compose in Justfile started in vim-dispatch immediately terminates

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [kaihowl/dotfiles#222]
Calling the same justfile from the command line and ctrl-c there, works as expected: The graceful shutdown is executed. Only with tmux+vim-dispatch we run into this issue.

**Comment by KaiHoewelmeyer-TomTom** [comment]
Can be reproduced with 

```test.sh
#!/bin/zsh
rm -rf output.log
function cleanup() {
  echo "sleeping 2 seconds" >> output.log
  echo "sleeping 2 seconds"
  sleep 2
  echo "reach end of trap" >> output.log
}
trap "cleanup" SIGINT
sleep 5
echo "Reached end of execution" >> output.log
```

```.VimMakefile
default:
	./test.sh
```

Works with `just -f .VimMakefile` in zsh directly. Using `ctrl-c` there, leads to the expected 2 seconds wait and all log messages are output to `output.log`. When calling the same from vim with vim-dispatch and its (non-interactive programs permitting) `Dispatch` command, the command is prematurely killed. Only the initial "sleeping 2 seconds" from the trap is emitted into the `output.log`.

**Comment by KaiHoewelmeyer-TomTom** [comment]
Even when reverting to `0766150` (before just was used) the same behavior is observed with make.

**Comment by KaiHoewelmeyer-TomTom** [comment]
This was broken by upstream vim-dispatch in https://github.com/tpope/vim-dispatch/commit/3505862b3898be5db3c78ba1b92c703349478d68.

**Comment by KaiHoewelmeyer-TomTom** [comment]
Created an upstream ticket https://github.com/tpope/vim-dispatch/issues/326 asking for advice.

**Comment by kaihowl** [comment]
Replaced by #239
