### ISSUE TITLE
Consider adding a default 100 chars limit for python

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [kaihowl/dotfiles#223]
~/.config/pycodestyle could be configured to read:
```
[pycodestyle]
max-line-length = 100
```

This would silence many faulty line changes from autoformatting where project specific configuration is in non-standard places.

**Comment by kaihowl** [comment]
Could not get autopep8 to properly wrap lines after 80 chars locally. To be checked again on Ubuntu machine.

**Comment by kaihowl** [comment]
Also could not reproduce on fresh Ubuntu 20.04 machine.
