### ISSUE TITLE
Editing of global task config broken

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [kaihowl/dotfiles#245]
`:AsyncTaskEdit!` incorrectly opens `~/.config/tasks.ini` instead of `~/.config/nvim/tasks.ini`. Maybe this has something to do with the disabled confirmation of the task filename?

**Comment by kaihowl** [comment]
On macOS this is not broken. Cannot reproduce there.

**Comment by kaihowl** [comment]
Also cannot reproduce on a clean Ubuntu 20.04 system.
