### ISSUE TITLE
Saving finished terminal buffer errors out

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [kaihowl/dotfiles#250]
When running
`:AsyncRun -mode=term echo test`
`jj`
`:sav /tmp/test.log`

I get
`E676: No matching autocommands for acwrite buffer`.

**Comment by kaihowl** [comment]
User error: Must use `:write <somefile>` instead. The terminal buffer has `buftype=terminal` and cannot be saved under its name. But it can be written out to a different file.
