### ISSUE TITLE
Running asynctask and Rg uses same quickfix window

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [kaihowl/dotfiles#268]
1. run a long running aynctask (e.g., compilation) with continuous output
2. Use :Rg in parallel

The output gets interleaved in the same quickfix window.

**Comment by kaihowl** [comment]
This also applies to `view_merge_request` et al.

**Comment by kaihowl** [comment]
Known upstream: https://github.com/skywind3000/asyncrun.vim/issues/73

**Comment by kaihowl** [comment]
Pending PR https://github.com/skywind3000/asyncrun.vim/pull/239
