### ISSUE TITLE
Running script/install opens zsh prompt and stops

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [kaihowl/dotfiles#298]
When running `script/install` from an interactive terminal, it seems that during `zsh/install.sh` a zsh prompt is opened and waits for input. This stalls/stops the unattended installation.

Only when `exit`ing the prompt, the installation continues.

**Comment by kaihowl** [comment]
Note to self: Observed on Ubuntu after omz had an update as well.
