### ISSUE TITLE
alacritty outdated on Ubuntu

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [kaihowl/dotfiles#326]
We have 0.8.0 in snap. It was not updated since mid 2021. We now have 0.10.1 available.

**Comment by kaihowl** [comment]
Trying to update the snap: https://github.com/snapcrafters/alacritty/pull/4

Worst case:
- Compile ourselves and push somewhere?
- Intake ppa (untrusted).

**Comment by kaihowl** [comment]
PPA: https://launchpad.net/~aslatter/+archive/ubuntu/ppa/+packages
