### ISSUE TITLE
Edge colorscheme broken after latest update

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [kaihowl/dotfiles#408]
```
E121: Undefined variable: s:palette
E116: Invalid arguments for function edge#highlight
```

Happens when opening a markdown file.

**Comment by kaihowl** [comment]
Fixed with a removal of `after/syntax` files. Also discovered that `edge_better_performance` was removed during the refactoring of the dynamic color scheme switching. Fixed that.
