### ISSUE TITLE
Ditch exuberant ctags + tagbar?

### ISSUE THREAD

**Issue by kaihowl** [kaihowl/dotfiles#547]
Could this be replaced by lsp? What about file types without lsp support?

Is there a tree-sitter based alternative?

Dropping would remove the exuberant-ctags dependency and clean up further.

**Comment by KaiHoewelmeyer-TomTom** [comment]
Try to use https://github.com/stevearc/aerial.nvim.

**Comment by KaiHoewelmeyer-TomTom** [comment]
aerial.nvim requires a full setup of treesitter to work for non-LSP files. Parked until #654 is done.

**Comment by KaiHoewelmeyer-TomTom** [comment]
Tested a little more: aerial uses query files to get relevant symbols out of tree sitter. Aerial supports less filetypes than exuberant ctags (e.g., kotlin is missing). Moreover, the query files are sometimes more limited (even with adjusting aerial_filter). Example here: bash/zsh is only showing functions. Aliases (which exuberant has) are not [defined](https://github.com/stevearc/aerial.nvim/blob/master/queries/bash/aerial.scm). Without more time investment for upstreaming improvements, there is not that much benefit. Moreover, on net we are not dropping a dependency.
