### ISSUE TITLE
Explore https://github.com/agkozak/zsh-z

### ISSUE THREAD

**Issue by kaihowl** [kaihowl/dotfiles#603]
Can this replace zoxide? Or can zoxide be convinced to prepopulate a cd command?

There is https://github.com/marlonrichert/zsh-autocomplete which offers now out of the box support and real time completions. It used to explicitly offer zoxide support as well. This can still be added as a custom backend.

What do I want out of this?

A simpler way to maintain a recent list of directories. It should offer real-time completions. It should rank by both frequency as well as recency.

**Comment by KaiHoewelmeyer-TomTom** [comment]
zsh-autocomplete works well. Pair with zsh-autosuggestions as suggested [here](https://www.reddit.com/r/zsh/comments/v08lsx/zshautocomplete_vs_zshautosuggestions_vs_fig/).

**Comment by KaiHoewelmeyer-TomTom** [comment]
Combine "z", "autosugestion", and "autocomplete". This is all working well. But the startup time is terrible (even without the additions). Maybe time to look into something other than omz? E.g., https://github.com/romkatv/zsh4humans?

**Comment by kaihowl** [comment]
Done
