### ISSUE TITLE
"alacritty" is already installed

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [kaihowl/dotfiles#605]
```
Running \e[32m./alacritty/install.sh\e[0m
Error: Cask 'alacritty' is already installed.
```
- [x] Work around
- [x] File ticket upstream
- [x] Fix upstream
- [x] Remove work around
- [x] For casks, check for installed, then upgrade.

**Comment by KaiHoewelmeyer-TomTom** [comment]
This was broken by Homebrew/brew#15273 (result from bisecting, detecting when `brew install alacritty` became a hard error).

**Comment by kaihowl** [comment]
Filed https://github.com/Homebrew/brew/issues/15295.
