### ISSUE TITLE
Error in nvim install

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [kaihowl/dotfiles#649]
```
Error detected while processing command line..function <SNR>2_clean[13]..<SNR>2_git_validate:
line   36:
E688: More targets than List items
```

- [ ] Safe guard invocation by checking for empty `v:errmsg` before exiting?

**Comment by kaihowl** [comment]
Asking for help / clarification in https://github.com/junegunn/vim-plug/issues/1253.

**Comment by kaihowl** [comment]
Not a current issue. Question / improvement upstream tracked.
