### ISSUE TITLE
precompile zsh plugins

### ISSUE THREAD

**Issue by kaihowl** [kaihowl/dotfiles#682]

**Comment by KaiHoewelmeyer-TomTom** [comment]
Powerlevel10k already precompiles the majority of the files (see [here](https://github.com/romkatv/powerlevel10k/blob/862440ae112603c8e2d202f6edb94eeaa1509120/powerlevel10k.zsh-theme#L70)). The added benefit of doing something like [this](https://unix.stackexchange.com/questions/454126/automatically-use-zwc-version-of-a-sourced-file/455097#455097) is about 10 ms deducted from about 53 ms on the work MPB. Not worth it in absolute terms. Discarding.
