### ISSUE TITLE
Don't add a semicolon when reusing history in zsh

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [kaihowl/dotfiles#691]

**Comment by kaihowl** [comment]
Related to https://github.com/marlonrichert/zsh-autocomplete/issues/361.

Not possible to remove at the moment. When pressing space, the semicolon disappears. Nuisance is only when accepting the current match and pressing enter. Then a new instance with the added semicolon is added to the history.

**Comment by KaiHoewelmeyer-TomTom** [comment]
I cannot reproduce anymore.
